<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecFile>../../Octokit.GraphQL.nuspec</NuspecFile>
    <NuspecBasePath>../..</NuspecBasePath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Octokit.GraphQL\Octokit.GraphQL.csproj" />
  </ItemGroup>

</Project>
