namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AcceptEnterpriseMemberInvitation
    /// </summary>
    public class AcceptEnterpriseMemberInvitationInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The id of the invitation being accepted
        /// </summary>
        public ID InvitationId { get; set; }
    }
}