namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AcceptEnterpriseMemberInvitation.
    /// </summary>
    public class AcceptEnterpriseMemberInvitationPayload : QueryableValue<AcceptEnterpriseMemberInvitationPayload>
    {
        internal AcceptEnterpriseMemberInvitationPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The invitation that was accepted.
        /// </summary>
        public EnterpriseMemberInvitation Invitation => this.CreateProperty(x => x.Invitation, Octokit.GraphQL.Model.EnterpriseMemberInvitation.Create);

        /// <summary>
        /// A message confirming the result of accepting an unaffiliated member invitation.
        /// </summary>
        public string Message { get; }

        internal static AcceptEnterpriseMemberInvitationPayload Create(Expression expression)
        {
            return new AcceptEnterpriseMemberInvitationPayload(expression);
        }
    }
}