namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of ConvertProjectV2DraftIssueItemToIssue.
    /// </summary>
    public class ConvertProjectV2DraftIssueItemToIssuePayload : QueryableValue<ConvertProjectV2DraftIssueItemToIssuePayload>
    {
        internal ConvertProjectV2DraftIssueItemToIssuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated project item.
        /// </summary>
        public ProjectV2Item Item => this.CreateProperty(x => x.Item, Octokit.GraphQL.Model.ProjectV2Item.Create);

        internal static ConvertProjectV2DraftIssueItemToIssuePayload Create(Expression expression)
        {
            return new ConvertProjectV2DraftIssueItemToIssuePayload(expression);
        }
    }
}