namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateProjectV2StatusUpdate.
    /// </summary>
    public class CreateProjectV2StatusUpdatePayload : QueryableValue<CreateProjectV2StatusUpdatePayload>
    {
        internal CreateProjectV2StatusUpdatePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The status update updated in the project.
        /// </summary>
        public ProjectV2StatusUpdate StatusUpdate => this.CreateProperty(x => x.StatusUpdate, Octokit.GraphQL.Model.ProjectV2StatusUpdate.Create);

        internal static CreateProjectV2StatusUpdatePayload Create(Expression expression)
        {
            return new CreateProjectV2StatusUpdatePayload(expression);
        }
    }
}