namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateDeployment.
    /// </summary>
    public class CreateDeploymentPayload : QueryableValue<CreateDeploymentPayload>
    {
        internal CreateDeploymentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// True if the default branch has been auto-merged into the deployment ref.
        /// </summary>
        public bool? AutoMerged { get; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The new deployment.
        /// </summary>
        public Deployment Deployment => this.CreateProperty(x => x.Deployment, Octokit.GraphQL.Model.Deployment.Create);

        internal static CreateDeploymentPayload Create(Expression expression)
        {
            return new CreateDeploymentPayload(expression);
        }
    }
}