namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateProjectV2StatusUpdate
    /// </summary>
    public class CreateProjectV2StatusUpdateInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the Project to create the status update in.
        /// </summary>
        public ID ProjectId { get; set; }

        /// <summary>
        /// The start date of the status update.
        /// </summary>
        public string StartDate { get; set; }

        /// <summary>
        /// The target date of the status update.
        /// </summary>
        public string TargetDate { get; set; }

        /// <summary>
        /// The status of the status update.
        /// </summary>
        public ProjectV2StatusUpdateStatus? Status { get; set; }

        /// <summary>
        /// The body of the status update.
        /// </summary>
        public string Body { get; set; }
    }
}