namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateDeploymentStatus.
    /// </summary>
    public class CreateDeploymentStatusPayload : QueryableValue<CreateDeploymentStatusPayload>
    {
        internal CreateDeploymentStatusPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The new deployment status.
        /// </summary>
        public DeploymentStatus DeploymentStatus => this.CreateProperty(x => x.DeploymentStatus, Octokit.GraphQL.Model.DeploymentStatus.Create);

        internal static CreateDeploymentStatusPayload Create(Expression expression)
        {
            return new CreateDeploymentStatusPayload(expression);
        }
    }
}