namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateLabel
    /// </summary>
    public class CreateLabelInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Node ID of the repository.
        /// </summary>
        public ID RepositoryId { get; set; }

        /// <summary>
        /// A 6 character hex code, without the leading #, identifying the color of the label.
        /// </summary>
        public string Color { get; set; }

        /// <summary>
        /// The name of the label.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// A brief description of the label, such as its purpose.
        /// </summary>
        public string Description { get; set; }
    }
}