namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeletePackageVersion
    /// </summary>
    public class DeletePackageVersionInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the package version to be deleted.
        /// </summary>
        public ID PackageVersionId { get; set; }
    }
}