namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteLabel.
    /// </summary>
    public class DeleteLabelPayload : QueryableValue<DeleteLabelPayload>
    {
        internal DeleteLabelPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        internal static DeleteLabelPayload Create(Expression expression)
        {
            return new DeleteLabelPayload(expression);
        }
    }
}