namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteProjectV2StatusUpdate.
    /// </summary>
    public class DeleteProjectV2StatusUpdatePayload : QueryableValue<DeleteProjectV2StatusUpdatePayload>
    {
        internal DeleteProjectV2StatusUpdatePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The ID of the deleted status update.
        /// </summary>
        public ID? DeletedStatusUpdateId { get; }

        /// <summary>
        /// The project the deleted status update was in.
        /// </summary>
        public ProjectV2 ProjectV2 => this.CreateProperty(x => x.ProjectV2, Octokit.GraphQL.Model.ProjectV2.Create);

        internal static DeleteProjectV2StatusUpdatePayload Create(Expression expression)
        {
            return new DeleteProjectV2StatusUpdatePayload(expression);
        }
    }
}