namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of ImportProject
    /// </summary>
    public class ImportProjectInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The name of the Organization or User to create the Project under.
        /// </summary>
        public string OwnerName { get; set; }

        /// <summary>
        /// The name of Project.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The description of Project.
        /// </summary>
        public string Body { get; set; }

        /// <summary>
        /// Whether the Project is public or not.
        /// </summary>
        public bool? Public { get; set; }

        /// <summary>
        /// A list of columns containing issues and pull requests.
        /// </summary>
        public IEnumerable<ProjectColumnImport> ColumnImports { get; set; }
    }
}