namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of InviteEnterpriseMember.
    /// </summary>
    public class InviteEnterpriseMemberPayload : QueryableValue<InviteEnterpriseMemberPayload>
    {
        internal InviteEnterpriseMemberPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The created enterprise member invitation.
        /// </summary>
        public EnterpriseMemberInvitation Invitation => this.CreateProperty(x => x.Invitation, Octokit.GraphQL.Model.EnterpriseMemberInvitation.Create);

        internal static InviteEnterpriseMemberPayload Create(Expression expression)
        {
            return new InviteEnterpriseMemberPayload(expression);
        }
    }
}