namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of InviteEnterpriseMember
    /// </summary>
    public class InviteEnterpriseMemberInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the enterprise to which you want to invite an unaffiliated member.
        /// </summary>
        public ID EnterpriseId { get; set; }

        /// <summary>
        /// The login of a user to invite as an unaffiliated member.
        /// </summary>
        public string Invitee { get; set; }

        /// <summary>
        /// The email of the person to invite as an unaffiliated member.
        /// </summary>
        public string Email { get; set; }
    }
}