namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of PinEnvironment
    /// </summary>
    public class PinEnvironmentInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the environment to modify
        /// </summary>
        public ID EnvironmentId { get; set; }

        /// <summary>
        /// The desired state of the environment. If true, environment will be pinned. If false, it will be unpinned.
        /// </summary>
        public bool Pinned { get; set; }
    }
}