namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of PinEnvironment.
    /// </summary>
    public class PinEnvironmentPayload : QueryableValue<PinEnvironmentPayload>
    {
        internal PinEnvironmentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The environment that was pinned
        /// </summary>
        public Environment Environment => this.CreateProperty(x => x.Environment, Octokit.GraphQL.Model.Environment.Create);

        /// <summary>
        /// The pinned environment if we pinned
        /// </summary>
        public PinnedEnvironment PinnedEnvironment => this.CreateProperty(x => x.PinnedEnvironment, Octokit.GraphQL.Model.PinnedEnvironment.Create);

        internal static PinEnvironmentPayload Create(Expression expression)
        {
            return new PinEnvironmentPayload(expression);
        }
    }
}