namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of ReorderEnvironment
    /// </summary>
    public class ReorderEnvironmentInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the environment to modify
        /// </summary>
        public ID EnvironmentId { get; set; }

        /// <summary>
        /// The desired position of the environment
        /// </summary>
        public int Position { get; set; }
    }
}