namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of ReorderEnvironment.
    /// </summary>
    public class ReorderEnvironmentPayload : QueryableValue<ReorderEnvironmentPayload>
    {
        internal ReorderEnvironmentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The environment that was reordered
        /// </summary>
        public Environment Environment => this.CreateProperty(x => x.Environment, Octokit.GraphQL.Model.Environment.Create);

        internal static ReorderEnvironmentPayload Create(Expression expression)
        {
            return new ReorderEnvironmentPayload(expression);
        }
    }
}