namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateProjectV2StatusUpdate.
    /// </summary>
    public class UpdateProjectV2StatusUpdatePayload : QueryableValue<UpdateProjectV2StatusUpdatePayload>
    {
        internal UpdateProjectV2StatusUpdatePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The status update updated in the project.
        /// </summary>
        public ProjectV2StatusUpdate StatusUpdate => this.CreateProperty(x => x.StatusUpdate, Octokit.GraphQL.Model.ProjectV2StatusUpdate.Create);

        internal static UpdateProjectV2StatusUpdatePayload Create(Expression expression)
        {
            return new UpdateProjectV2StatusUpdatePayload(expression);
        }
    }
}