namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateTeamReviewAssignment.
    /// </summary>
    public class UpdateTeamReviewAssignmentPayload : QueryableValue<UpdateTeamReviewAssignmentPayload>
    {
        internal UpdateTeamReviewAssignmentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The team that was modified
        /// </summary>
        public Team Team => this.CreateProperty(x => x.Team, Octokit.GraphQL.Model.Team.Create);

        internal static UpdateTeamReviewAssignmentPayload Create(Expression expression)
        {
            return new UpdateTeamReviewAssignmentPayload(expression);
        }
    }
}