namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateLabel.
    /// </summary>
    public class UpdateLabelPayload : QueryableValue<UpdateLabelPayload>
    {
        internal UpdateLabelPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated label.
        /// </summary>
        public Label Label => this.CreateProperty(x => x.Label, Octokit.GraphQL.Model.Label.Create);

        internal static UpdateLabelPayload Create(Expression expression)
        {
            return new UpdateLabelPayload(expression);
        }
    }
}