namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateLabel
    /// </summary>
    public class UpdateLabelInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Node ID of the label to be updated.
        /// </summary>
        public ID Id { get; set; }

        /// <summary>
        /// A 6 character hex code, without the leading #, identifying the updated color of the label.
        /// </summary>
        public string Color { get; set; }

        /// <summary>
        /// A brief description of the label, such as its purpose.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The updated name of the label.
        /// </summary>
        public string Name { get; set; }
    }
}