namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AcceptTopicSuggestion
    /// </summary>
    public class AcceptTopicSuggestionInput
    {
        public ID RepositoryId { get; set; }

        public string Name { get; set; }

        public string ClientMutationId { get; set; }
    }
}