namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AcceptTopicSuggestion
    /// </summary>
    public class AcceptTopicSuggestionPayload : QueryableValue<AcceptTopicSuggestionPayload>
    {
        internal AcceptTopicSuggestionPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The accepted topic.
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `topic` will change from `Topic!` to `Topic`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public Topic Topic => this.CreateProperty(x => x.Topic, Octokit.GraphQL.Model.Topic.Create);

        internal static AcceptTopicSuggestionPayload Create(Expression expression)
        {
            return new AcceptTopicSuggestionPayload(expression);
        }
    }
}