namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AddPullRequestReviewComment
    /// </summary>
    public class AddPullRequestReviewCommentInput
    {
        public ID PullRequestReviewId { get; set; }

        public string CommitOID { get; set; }

        public string Body { get; set; }

        public string Path { get; set; }

        public int? Position { get; set; }

        public ID? InReplyTo { get; set; }

        public string ClientMutationId { get; set; }
    }
}