namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AddPullRequestReviewComment
    /// </summary>
    public class AddPullRequestReviewCommentPayload : QueryableValue<AddPullRequestReviewCommentPayload>
    {
        public AddPullRequestReviewCommentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The newly created comment.
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `comment` will change from `PullRequestReviewComment!` to `PullRequestReviewComment`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public PullRequestReviewComment Comment => this.CreateProperty(x => x.Comment, Octokit.GraphQL.Model.PullRequestReviewComment.Create);

        /// <summary>
        /// The edge from the review's comment connection.
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `commentEdge` will change from `PullRequestReviewCommentEdge!` to `PullRequestReviewCommentEdge`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public PullRequestReviewCommentEdge CommentEdge => this.CreateProperty(x => x.CommentEdge, Octokit.GraphQL.Model.PullRequestReviewCommentEdge.Create);

        internal static AddPullRequestReviewCommentPayload Create(Expression expression)
        {
            return new AddPullRequestReviewCommentPayload(expression);
        }
    }
}