namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AddProjectCard
    /// </summary>
    public class AddProjectCardPayload : QueryableValue<AddProjectCardPayload>
    {
        public AddProjectCardPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// The edge from the ProjectColumn's card connection.
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `cardEdge` will change from `ProjectCardEdge!` to `ProjectCardEdge`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public ProjectCardEdge CardEdge => this.CreateProperty(x => x.CardEdge, Octokit.GraphQL.Model.ProjectCardEdge.Create);

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The ProjectColumn
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `projectColumn` will change from `Project!` to `Project`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public Project ProjectColumn => this.CreateProperty(x => x.ProjectColumn, Octokit.GraphQL.Model.Project.Create);

        internal static AddProjectCardPayload Create(Expression expression)
        {
            return new AddProjectCardPayload(expression);
        }
    }
}