namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AddProjectColumn
    /// </summary>
    public class AddProjectColumnInput
    {
        public string ClientMutationId { get; set; }

        public string ProjectId { get; set; }

        public string Name { get; set; }
    }
}