namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AddProjectCard
    /// </summary>
    public class AddProjectCardInput
    {
        public ID ProjectColumnId { get; set; }

        public ID? ContentId { get; set; }

        public string Note { get; set; }

        public string ClientMutationId { get; set; }
    }
}