namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AddStar
    /// </summary>
    public class AddStarInput
    {
        public ID StarrableId { get; set; }

        public string ClientMutationId { get; set; }
    }
}