namespace Octokit.GraphQL.Model
{
    using System;
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of AddStar
    /// </summary>
    public class AddStarInput
    {
        public string ClientMutationId { get; set; }

        public string StarrableId { get; set; }
    }
}