namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AddStar
    /// </summary>
    public class AddStarInput
    {
        /// <summary>
        /// The Starrable ID to star.
        /// </summary>
        public string StarrableId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}