namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CancelBusinessAdminInvitation
    /// </summary>
    public class CancelBusinessAdminInvitationInput
    {
        /// <summary>
        /// The Node ID of the pending business admin invitation.
        /// </summary>
        public ID InvitationId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}