namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateRepositoryRuleset
    /// </summary>
    public class CreateRepositoryRulesetInput
    {
        /// <summary>
        /// The global relay id of the source in which a new ruleset should be created in.
        /// </summary>
        public ID SourceId { get; set; }

        /// <summary>
        /// The name of the ruleset.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The target of the ruleset.
        /// </summary>
        public RepositoryRulesetTarget? Target { get; set; }

        /// <summary>
        /// The list of rules for this ruleset
        /// </summary>
        public IEnumerable<RepositoryRuleInput> Rules { get; set; }

        /// <summary>
        /// The set of conditions for this ruleset
        /// </summary>
        public RepositoryRuleConditionsInput Conditions { get; set; }

        /// <summary>
        /// The enforcement level for this ruleset
        /// </summary>
        public RuleEnforcement Enforcement { get; set; }

        /// <summary>
        /// The bypass mode for this ruleset
        /// </summary>
        public RuleBypassMode? BypassMode { get; set; }

        /// <summary>
        /// A list of Team or App IDs allowed to bypass rules in this ruleset.
        /// </summary>
        public IEnumerable<ID> BypassActorIds { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}