namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateTeamDiscussion
    /// </summary>
    public class CreateTeamDiscussionPayload : QueryableValue<CreateTeamDiscussionPayload>
    {
        internal CreateTeamDiscussionPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The new discussion.
        /// </summary>
        public TeamDiscussion TeamDiscussion => this.CreateProperty(x => x.TeamDiscussion, Octokit.GraphQL.Model.TeamDiscussion.Create);

        internal static CreateTeamDiscussionPayload Create(Expression expression)
        {
            return new CreateTeamDiscussionPayload(expression);
        }
    }
}