namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateProject
    /// </summary>
    public class CreateProjectInput
    {
        public ID OwnerId { get; set; }

        public string Name { get; set; }

        public string Body { get; set; }

        public string ClientMutationId { get; set; }
    }
}