namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeclineTopicSuggestion
    /// </summary>
    public class DeclineTopicSuggestionInput
    {
        public ID RepositoryId { get; set; }

        public string Name { get; set; }

        public TopicSuggestionDeclineReason Reason { get; set; }

        public string ClientMutationId { get; set; }
    }
}