namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteBranchProtectionRule
    /// </summary>
    public class DeleteBranchProtectionRuleInput
    {
        public ID BranchProtectionRuleId { get; set; }

        public string ClientMutationId { get; set; }
    }
}