namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeletePullRequestReview
    /// </summary>
    public class DeletePullRequestReviewInput
    {
        public string ClientMutationId { get; set; }

        public string PullRequestReviewId { get; set; }
    }
}