namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteProjectColumn
    /// </summary>
    public class DeleteProjectColumnInput
    {
        public string ClientMutationId { get; set; }

        public string ColumnId { get; set; }
    }
}