namespace Octokit.GraphQL.Model
{
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of DeleteProjectCard
    /// </summary>
    public class DeleteProjectCardInput
    {
        public string ClientMutationId { get; set; }

        public string CardId { get; set; }
    }
}