namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteProjectCard
    /// </summary>
    public class DeleteProjectCardInput
    {
        public ID CardId { get; set; }

        public string ClientMutationId { get; set; }
    }
}