namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteProject
    /// </summary>
    public class DeleteProjectInput
    {
        public ID ProjectId { get; set; }

        public string ClientMutationId { get; set; }
    }
}