namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteProjectColumn
    /// </summary>
    public class DeleteProjectColumnPayload : QueryableValue<DeleteProjectColumnPayload>
    {
        public DeleteProjectColumnPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The deleted column ID.
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `deletedColumnId` will change from `ID!` to `ID`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public ID DeletedColumnId { get; }

        /// <summary>
        /// The project the deleted column was in.
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `project` will change from `Project!` to `Project`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public Project Project => this.CreateProperty(x => x.Project, Octokit.GraphQL.Model.Project.Create);

        internal static DeleteProjectColumnPayload Create(Expression expression)
        {
            return new DeleteProjectColumnPayload(expression);
        }
    }
}