namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DismissPullRequestReview
    /// </summary>
    public class DismissPullRequestReviewPayload : QueryableValue<DismissPullRequestReviewPayload>
    {
        public DismissPullRequestReviewPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The dismissed pull request review.
        /// </summary>
        public PullRequestReview PullRequestReview => this.CreateProperty(x => x.PullRequestReview, Octokit.GraphQL.Model.PullRequestReview.Create);

        internal static DismissPullRequestReviewPayload Create(IQueryProvider provider, Expression expression)
        {
            return new DismissPullRequestReviewPayload(provider, expression);
        }
    }
}