namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of InviteBusinessBillingManager
    /// </summary>
    public class InviteBusinessBillingManagerInput
    {
        /// <summary>
        /// The ID of the business to which you want to invite a billing manager.
        /// </summary>
        public ID BusinessId { get; set; }

        /// <summary>
        /// The login of a user to invite as a billing manager.
        /// </summary>
        public string Invitee { get; set; }

        /// <summary>
        /// The email of the person to invite as a billing manager.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}