namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of MinimizeComment
    /// </summary>
    public class MinimizeCommentInput
    {
        public ID SubjectId { get; set; }

        public ReportedContentClassifiers Classifier { get; set; }

        public string ClientMutationId { get; set; }
    }
}