namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of MoveProjectCard
    /// </summary>
    public class MoveProjectCardInput
    {
        public ID CardId { get; set; }

        public ID ColumnId { get; set; }

        public ID? AfterCardId { get; set; }

        public string ClientMutationId { get; set; }
    }
}