namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of PinIssue
    /// </summary>
    public class PinIssueInput
    {
        public ID IssueId { get; set; }

        public string ClientMutationId { get; set; }
    }
}