namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RegenerateBusinessIdentityProviderRecoveryCodes
    /// </summary>
    public class RegenerateBusinessIdentityProviderRecoveryCodesInput
    {
        /// <summary>
        /// The ID of the business on which to set an Identity Provider.
        /// </summary>
        public ID BusinessId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}