namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RemoveOutsideCollaborator
    /// </summary>
    public class RemoveOutsideCollaboratorInput
    {
        public ID UserId { get; set; }

        public ID OrganizationId { get; set; }

        public string ClientMutationId { get; set; }
    }
}