namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RemoveStar
    /// </summary>
    public class RemoveStarInput
    {
        public string ClientMutationId { get; set; }

        public string StarrableId { get; set; }
    }
}