namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RemoveBusinessIdentityProvider
    /// </summary>
    public class RemoveBusinessIdentityProviderInput
    {
        /// <summary>
        /// The ID of the business from which to remove the Identity Provider.
        /// </summary>
        public ID BusinessId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}