namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RemoveEnterpriseOrganization
    /// </summary>
    public class RemoveEnterpriseOrganizationInput
    {
        /// <summary>
        /// The ID of the enterprise from which the organization should be removed.
        /// </summary>
        public string EnterpriseId { get; set; }

        /// <summary>
        /// The ID of the organization to remove from the enterprise.
        /// </summary>
        public string OrganizationId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}