namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RequestReviews
    /// </summary>
    public class RequestReviewsInput
    {
        public ID PullRequestId { get; set; }

        public IEnumerable<ID> UserIds { get; set; }

        public IEnumerable<ID> TeamIds { get; set; }

        public bool? Union { get; set; }

        public string ClientMutationId { get; set; }
    }
}