namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RequestReviews
    /// </summary>
    public class RequestReviewsInput
    {
        public string ClientMutationId { get; set; }

        public string PullRequestId { get; set; }

        public IEnumerable<string> UserIds { get; set; }

        public IEnumerable<string> TeamIds { get; set; }

        public bool? Union { get; set; }
    }
}