namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of ResolveReviewThread
    /// </summary>
    public class ResolveReviewThreadInput
    {
        /// <summary>
        /// The ID of the thread to resolve
        /// </summary>
        public string ThreadId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}