namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of SetBusinessIdentityProvider
    /// </summary>
    public class SetBusinessIdentityProviderInput
    {
        /// <summary>
        /// The ID of the business on which to set an Identity Provider.
        /// </summary>
        public ID BusinessId { get; set; }

        /// <summary>
        /// The URL endpoint for the Identity Provider's SAML SSO.
        /// </summary>
        public string SsoUrl { get; set; }

        /// <summary>
        /// The Issuer Entity ID for the SAML Identity Provider
        /// </summary>
        public string Issuer { get; set; }

        /// <summary>
        /// The x509 certificate used by the Identity Provider to sign assertions and responses.
        /// </summary>
        public string IdpCertificate { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}