namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of TransferIssue
    /// </summary>
    public class TransferIssueInput
    {
        /// <summary>
        /// The Node ID of the issue to be transferred
        /// </summary>
        public string IssueId { get; set; }

        /// <summary>
        /// The Node ID of the repository the issue should be transferred to
        /// </summary>
        public string RepositoryId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}