namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnlinkRepositoryFromProject
    /// </summary>
    public class UnlinkRepositoryFromProjectInput
    {
        /// <summary>
        /// The ID of the Project linked to the Repository.
        /// </summary>
        public string ProjectId { get; set; }

        /// <summary>
        /// The ID of the Repository linked to the Project.
        /// </summary>
        public string RepositoryId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}