namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnlockLockable
    /// </summary>
    public class UnlockLockableInput
    {
        public ID LockableId { get; set; }

        public string ClientMutationId { get; set; }
    }
}