namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnminimizeComment
    /// </summary>
    public class UnminimizeCommentInput
    {
        public ID SubjectId { get; set; }

        public string ClientMutationId { get; set; }
    }
}