namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnresolveReviewThread
    /// </summary>
    public class UnresolveReviewThreadInput
    {
        public ID ThreadId { get; set; }

        public string ClientMutationId { get; set; }
    }
}