namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;;

    /// <summary>
    /// Autogenerated input type of UnresolveReviewThread
    /// </summary>
    public class UnresolveReviewThreadInput
    {
        /// <summary>
        /// The ID of the thread to unresolve
        /// </summary>
        public ID ThreadId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}