namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateBusinessProfile
    /// </summary>
    public class UpdateBusinessProfileInput
    {
        /// <summary>
        /// The Business ID to update.
        /// </summary>
        public ID BusinessId { get; set; }

        /// <summary>
        /// The name of business.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The description of the business.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The URL of the business's website
        /// </summary>
        public string WebsiteUrl { get; set; }

        /// <summary>
        /// The location of the business
        /// </summary>
        public string Location { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}