namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateProjectColumn
    /// </summary>
    public class UpdateProjectColumnInput
    {
        public ID ProjectColumnId { get; set; }

        public string Name { get; set; }

        public string ClientMutationId { get; set; }
    }
}