namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateProject
    /// </summary>
    public class UpdateProjectInput
    {
        public ID ProjectId { get; set; }

        public string Name { get; set; }

        public string Body { get; set; }

        public ProjectState? State { get; set; }

        public bool? Public { get; set; }

        public string ClientMutationId { get; set; }
    }
}