namespace Octokit.GraphQL.Model
{
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of UpdateTopics
    /// </summary>
    public class UpdateTopicsInput
    {
        public string ClientMutationId { get; set; }

        public string RepositoryId { get; set; }

        public IQueryable<string> TopicNames { get; set; }
    }
}