namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateSubscription
    /// </summary>
    public class UpdateSubscriptionPayload : QueryableValue<UpdateSubscriptionPayload>
    {
        public UpdateSubscriptionPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The input subscribable entity.
        /// **Upcoming Change on 2019-01-01 UTC**
        /// **Description:** Type for `subscribable` will change from `Subscribable!` to `Subscribable`.
        /// **Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.
        /// </summary>
        public ISubscribable Subscribable => this.CreateProperty(x => x.Subscribable, Octokit.GraphQL.Model.Internal.StubISubscribable.Create);

        internal static UpdateSubscriptionPayload Create(Expression expression)
        {
            return new UpdateSubscriptionPayload(expression);
        }
    }
}