namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateProjectNextItemField
    /// </summary>
    public class UpdateProjectNextItemFieldPayload : QueryableValue<UpdateProjectNextItemFieldPayload>
    {
        internal UpdateProjectNextItemFieldPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated item.
        /// </summary>
        public ProjectNextItem ProjectNextItem => this.CreateProperty(x => x.ProjectNextItem, Octokit.GraphQL.Model.ProjectNextItem.Create);

        internal static UpdateProjectNextItemFieldPayload Create(Expression expression)
        {
            return new UpdateProjectNextItemFieldPayload(expression);
        }
    }
}