namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateCheckRun
    /// </summary>
    public class UpdateCheckRunInput
    {
        public ID RepositoryId { get; set; }

        public ID CheckRunId { get; set; }

        public string Name { get; set; }

        public string DetailsUrl { get; set; }

        public string ExternalId { get; set; }

        public RequestableCheckStatusState? Status { get; set; }

        public DateTimeOffset? StartedAt { get; set; }

        public CheckConclusionState? Conclusion { get; set; }

        public DateTimeOffset? CompletedAt { get; set; }

        public CheckRunOutput Output { get; set; }

        public IEnumerable<CheckRunAction> Actions { get; set; }

        public string ClientMutationId { get; set; }
    }
}