namespace Octokit.GraphQL.Model
{
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of UpdateProjectColumn
    /// </summary>
    public class UpdateProjectColumnInput
    {
        public string ClientMutationId { get; set; }

        public string ProjectColumnId { get; set; }

        public string Name { get; set; }
    }
}