namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateEnterpriseActionExecutionCapabilitySetting
    /// </summary>
    public class UpdateEnterpriseActionExecutionCapabilitySettingInput
    {
        /// <summary>
        /// The ID of the enterprise on which to set the members can create repositories setting.
        /// </summary>
        public ID EnterpriseId { get; set; }

        /// <summary>
        /// The value for the action execution capability setting on the enterprise.
        /// </summary>
        public ActionExecutionCapabilitySetting Capability { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}