namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateCheckSuitePreferences
    /// </summary>
    public class UpdateCheckSuitePreferencesInput
    {
        public ID RepositoryId { get; set; }

        public IEnumerable<CheckSuiteAutoTriggerPreference> AutoTriggerPreferences { get; set; }

        public string ClientMutationId { get; set; }
    }
}