namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateBusinessMembersCanInviteCollaboratorsSetting
    /// </summary>
    public class UpdateBusinessMembersCanInviteCollaboratorsSettingInput
    {
        /// <summary>
        /// The ID of the business on which to set the members can invite collaborators setting.
        /// </summary>
        public ID BusinessId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}