namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdatePullRequestReviewComment
    /// </summary>
    public class UpdatePullRequestReviewCommentInput
    {
        public ID PullRequestReviewCommentId { get; set; }

        public string Body { get; set; }

        public string ClientMutationId { get; set; }
    }
}