namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateSubscription
    /// </summary>
    public class UpdateSubscriptionInput
    {
        public string ClientMutationId { get; set; }

        public string SubscribableId { get; set; }

        public SubscriptionState State { get; set; }
    }
}