namespace Octoqit
{
    using System.Linq;
    using System.Linq.Expressions;
    using LinqToGraphQL;
    using LinqToGraphQL.Builders;

    /// <summary>
    /// Autogenerated return type of AddProjectCard
    /// </summary>
    public class AddProjectCardPayload : QueryEntity
    {
        public AddProjectCardPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// The edge from the ProjectColumn's card connection.
        /// </summary>
        public ProjectCardEdge CardEdge => this.CreateProperty(x => x.CardEdge, Octoqit.ProjectCardEdge.Create);

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The ProjectColumn
        /// </summary>
        public Project ProjectColumn => this.CreateProperty(x => x.ProjectColumn, Octoqit.Project.Create);

        internal static AddProjectCardPayload Create(IQueryProvider provider, Expression expression)
        {
            return new AddProjectCardPayload(provider, expression);
        }
    }
}