namespace Octoqit
{
    using System.Linq;
    using System.Linq.Expressions;
    using LinqToGraphQL;
    using LinqToGraphQL.Builders;

    /// <summary>
    /// Autogenerated return type of DeletePullRequestReview
    /// </summary>
    public class DeletePullRequestReviewPayload : QueryEntity
    {
        public DeletePullRequestReviewPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The deleted pull request review.
        /// </summary>
        public PullRequestReview PullRequestReview => this.CreateProperty(x => x.PullRequestReview, Octoqit.PullRequestReview.Create);

        internal static DeletePullRequestReviewPayload Create(IQueryProvider provider, Expression expression)
        {
            return new DeletePullRequestReviewPayload(provider, expression);
        }
    }
}