namespace Octoqit
{
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of RemoveOutsideCollaborator
    /// </summary>
    public class RemoveOutsideCollaboratorInput
    {
        public string ClientMutationId { get; set; }

        public string UserId { get; set; }

        public string OrganizationId { get; set; }
    }
}