namespace Octokit.GraphQL
{
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of RequestReviews
    /// </summary>
    public class RequestReviewsInput
    {
        public string ClientMutationId { get; set; }

        public string PullRequestId { get; set; }

        public IQueryable<string> UserIds { get; set; }

        public bool? Union { get; set; }
    }
}