namespace Octoqit
{
    using System.Linq;
    using System.Linq.Expressions;
    using LinqToGraphQL;
    using LinqToGraphQL.Builders;

    /// <summary>
    /// Autogenerated return type of RequestReviews
    /// </summary>
    public class RequestReviewsPayload : QueryEntity
    {
        public RequestReviewsPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The pull request that is getting requests.
        /// </summary>
        public PullRequest PullRequest => this.CreateProperty(x => x.PullRequest, Octoqit.PullRequest.Create);

        /// <summary>
        /// The edge from the pull request to the requested reviewers.
        /// </summary>
        public UserEdge RequestedReviewersEdge => this.CreateProperty(x => x.RequestedReviewersEdge, Octoqit.UserEdge.Create);

        internal static RequestReviewsPayload Create(IQueryProvider provider, Expression expression)
        {
            return new RequestReviewsPayload(provider, expression);
        }
    }
}