namespace Octoqit
{
    using System.Linq;
    using System.Linq.Expressions;
    using LinqToGraphQL;
    using LinqToGraphQL.Builders;

    /// <summary>
    /// Autogenerated return type of UpdatePullRequestReview
    /// </summary>
    public class UpdatePullRequestReviewPayload : QueryEntity
    {
        public UpdatePullRequestReviewPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated pull request review.
        /// </summary>
        public PullRequestReview PullRequestReview => this.CreateProperty(x => x.PullRequestReview, Octoqit.PullRequestReview.Create);

        internal static UpdatePullRequestReviewPayload Create(IQueryProvider provider, Expression expression)
        {
            return new UpdatePullRequestReviewPayload(provider, expression);
        }
    }
}