namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnlockLockable
    /// </summary>
    public class UnlockLockableInput
    {
        /// <summary>
        /// ID of the issue or pull request to be unlocked.
        /// </summary>
        public ID LockableId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}