namespace Octokit.GraphQL
{
    using System;
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of AcceptTopicSuggestion
    /// </summary>
    public class AcceptTopicSuggestionInput
    {
        public string ClientMutationId { get; set; }

        public string RepositoryId { get; set; }

        public string Name { get; set; }
    }
}