namespace Octokit.GraphQL
{
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of AddComment
    /// </summary>
    public class AddCommentInput
    {
        public string ClientMutationId { get; set; }

        public string SubjectId { get; set; }

        public string Body { get; set; }
    }
}