namespace Octokit.GraphQL
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeclineTopicSuggestion
    /// </summary>
    public class DeclineTopicSuggestionPayload : QueryEntity
    {
        public DeclineTopicSuggestionPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The declined topic.
        /// </summary>
        public Topic Topic => this.CreateProperty(x => x.Topic, Octokit.GraphQL.Topic.Create);

        internal static DeclineTopicSuggestionPayload Create(IQueryProvider provider, Expression expression)
        {
            return new DeclineTopicSuggestionPayload(provider, expression);
        }
    }
}