namespace Octokit.GraphQL
{
    using System;
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of DeleteProject
    /// </summary>
    public class DeleteProjectInput
    {
        public string ClientMutationId { get; set; }

        public string ProjectId { get; set; }
    }
}