namespace Octokit.GraphQL
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateSubscription
    /// </summary>
    public class UpdateSubscriptionPayload : QueryEntity
    {
        public UpdateSubscriptionPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The input subscribable entity.
        /// </summary>
        public ISubscribable Subscribable => this.CreateProperty(x => x.Subscribable, Octokit.GraphQL.Internal.StubISubscribable.Create);

        internal static UpdateSubscriptionPayload Create(IQueryProvider provider, Expression expression)
        {
            return new UpdateSubscriptionPayload(provider, expression);
        }
    }
}