namespace Octokit.GraphQL
{
    using System;
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of UpdatePullRequestReview
    /// </summary>
    public class UpdatePullRequestReviewInput
    {
        public string ClientMutationId { get; set; }

        public string PullRequestReviewId { get; set; }

        public string Body { get; set; }
    }
}