namespace Octokit.GraphQL
{
    using System;
    using System.Linq;

    /// <summary>
    /// Autogenerated input type of UpdateProjectCard
    /// </summary>
    public class UpdateProjectCardInput
    {
        public string ClientMutationId { get; set; }

        public string ProjectCardId { get; set; }

        public string Note { get; set; }
    }
}