namespace Octokit.GraphQL
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdatePullRequestReviewComment
    /// </summary>
    public class UpdatePullRequestReviewCommentPayload : QueryEntity
    {
        public UpdatePullRequestReviewCommentPayload(IQueryProvider provider, Expression expression) : base(provider, expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated comment.
        /// </summary>
        public PullRequestReviewComment PullRequestReviewComment => this.CreateProperty(x => x.PullRequestReviewComment, Octokit.GraphQL.PullRequestReviewComment.Create);

        internal static UpdatePullRequestReviewCommentPayload Create(IQueryProvider provider, Expression expression)
        {
            return new UpdatePullRequestReviewCommentPayload(provider, expression);
        }
    }
}